# Antecedentes:

Las agudas manifestaciones que sucedieron el 18 de octubre de 2019 se extendieron por más de cinco meses, y solo se detuvieron frente a la pandemia de Covid-19 que comenzó en marzo de 2020. Durante este periodo, las protestas iniciadas por estudiantes secundarios mostraron un amplio repertorio de acciones: las evasiones masivas en el metro de Santiago se transformaron en manifestaciones callejeras interrumpiendo el tránsito, barricadas y marchas no autorizadas por todo el país. La manifestación pacífica, daba paso a formas más violentas de protestas: incendios, daño al mobiliario público, saqueos a locales comerciales y enfrentamientos con Carabineros.

Desde el día 18 de octubre y durante diez días, el ex presidente Sebastián Piñera declara estado de excepción, habilitando el accionar de las fuerzas armadas en el control del orden público y decretando toque de queda. En este contexto, el debate sobre la protesta social y el accionar de Carabineros en la contención del orden público se polariza. Por un lado, el estallido delincuencial denunciado por el gobierno, frente a un “enemigo poderoso”  es seguido de iniciativas de ley “anti-barricadas” y “anti-encapuchados”, buscando aumentar las penas para quienes cometan estos delitos. Por otra parte, un sector de la población defiende el actuar de los llamados encapuchados, presentes en marchas y movilizaciones anteriores, que pasan a ser nombrados como manifestantes de primera línea, argumentando su actuar frente a la represión de Carabineros.

Frente a la masividad de las protestas, diversas instituciones, tanto nacionales como internacionales, cuestionaron el rol de Carabineros frente al control del orden público, argumentando una política deliberada para dañar manifestantes dada por los mandos de Carabineros (Amnistia Internacional, 2019) y un uso excesivo de la fuerza (Instituto Nacional de Derechos Humanos, 2020), poniendo en tela de juicio los métodos y la discrecionalidad de la institución en el control del orden público en el uso de armas no letales o menos letales como la escopeta antidisturbios, gases lacrimógenos y la acción de las fuerzas de orden público frente a la congregación de marchas pacíficas. 

Aunque organismos internacionales como Human Right Watch (2019) y la Comisión Interamericana de Derechos Humanos (2019) dieron cuenta de violaciones en los Derechos Humanos por parte de Carabineros en el marco del llamado estallido social, incluyendo el derecho a la vida y el derecho a reunirse pacíficamente, el debate no fue inequívoco, generando opiniones favorables hacia el actuar de Carabineros frente al denunciado estallido delincuencial, apoyando la legítima aspiración de la institución por controlar el orden público.

El ex candidato presidencial José Antonio Kast llegó a declarar que las violaciones masivas a los derechos humanos por parte de Carabineros no existieron, denunciando la violencia y la alteración del orden público como una estrategia sostenida por sectores de izquierda (Durán & Rojas, 2021). Sus dichos dejan entrever la opinión de un sector de la población que se identificó fuertemente con la institución policial, avalando sus acciones e invocando la necesidad de orden público frente a la radicalización de la protesta durante el estallido social, haciendo referencia a una mayoría silenciosa que buscaba la paz y la recuperación del orden público. 

El debate sobre el control del orden público por parte de Carabineros queda planteado, mas no resuelto: ¿hasta qué punto puede Carabineros intervenir por el control del orden público sin menoscabar el derecho a la reunión pacífica? El debate se enfría luego de la pandemia de Covid-19 (Nava & Grigera, 2022), dando paso a una discusión marcada principalmente por: 1. Una recesión económica con una tasa de inflación superior al 10% durante 2022 (García , 2022), y 2. Una crisis de seguridad pública, marcada por tres factores: la presión migratoria post Covid, el aumento de la delincuencia y los atentados en la Araucanía producto del conflicto mapuche (Heiss, 2023).

Como advertimos, la crisis de seguridad es uno de los elementos más resaltados en la opinión pública (CEP, 2023), esto se ha reflejado en un mayor apoyo a Carabineros en el combate contra la delincuencia (CADEM, 2023), generando un contexto marcado por la percepción generalizada de inseguridad, el aumento de la delincuencia y la migración descontrolada. 

Aunque el miedo al delito es un problema ampliamente estudiado, algunos autores (Vozmediano, San Juan , & Vergara, 2008), sugieren separar la percepción subjetiva de los individuos de los índices objetivos de seguridad y delito. Esto implica entender el miedo a la delincuencia más allá de una perspectiva criminológica, como parte de una temática mayor de la percepción de inseguridad (Muratori & Zubieta, 2013), que incluye no solo la delincuencia tradicional sino también el vandalismo, el terrorismo, u otras amenazas, en las que se puede incluir las protestas sociales.

Rottenbacher (2008, pág. 37), define el contexto socio-emocional como las representaciones colectivas de la situación sociopolítica de una nación, cargadas afectivamente, que predominan en una colectividad durante un período histórico y sociopolítico determinado. Estas representaciones influyen en las relaciones sociales dentro de esa colectividad y en sus representaciones sociales sobre el mundo, el presente y el futuro. 

Diversas investigaciones, incluso en el contexto latinoamericano (Rottenbacher de Rojas, Amaya , Genna, & Pulache, 2009), sugieren que la percepción de inseguridad incrementa más en quienes son renuentes a los cambios sociales. Las actitudes hacia el crimen, vigilancia y punitivismo expresan un mismo fenómeno emergente: están envueltos en lo que los individuos perciben como hostil, lo que quieren y como debe organizarse la sociedad (Gerber & Jackson, 2016, pág. 15).

La literatura converge en que hay cierta afinidad entre la percepción de miedo, amenaza y posturas conservadoras (Jost, Stern, Rule, & Sterling, 2017). Así mismo, la intolerancia a la ambigüedad, evitar la incertidumbre y la necesidad por orden y estructura han sido sistemáticamente relacionados positivamente con el conservadurismo político (Jost, Glaser, Kruglanski, & Sulloway, 2003).Otros estudios (Bonano & Jost, 2006 en Jost, Federico, & Napier, 2009), sugieren que el apoyo hacia actitudes conservadores y de derecha aumentan en periodos de inestabilidad política y económica, bajo la premisa de que la sensación de amenaza activa actitudes políticas y sociales que ofrecen soluciones simples pero rígidas en materia de seguridad (Thórisdóttir & Jost, 2011).

La propuesta de investigación busca indagar el proceso que opera en relación al miedo, el conservadurismo político de derecha y la justificación de la violencia policial en contexto de protesta. Específicamente, buscaremos ahondar en la forma en que influye el miedo a manifestantes de primera línea y el conservadurismo político de derecha, en la justificación de la violencia policial en el contexto de declive de la protesta social el año 2022. 

