# Marco Teórico:

### Perspectivas sobre la violencia

Cuando se estudia el uso de la fuerza por parte de la policía, se remite en esencia al carácter monopólico y legítimo de la fuerza por parte del Estado. Desde cierto momento hobbesiano en donde se cede el ejercicio de la violencia al Estado, o entendiendo el carácter monopólico y legítimo del uso de la fuerza como propiedad fundamental del Estado moderno en Weber (Trovero, 2020).  La idea del Estado parece inseparable de la violencia, aunque no sea reducible a esta. 

El término violencia, es usado para describir fenómenos y conductas tanto individuales como colectivas, por lo que resulta especialmente difícil de definir y estudiar (Wieviorka, 2009). Independiente de su relación con el concepto de Estado, las definiciones de la violencia son múltiples y provenientes desde distintas ciencias y corrientes teóricas. Respecto a que es la violencia, Bufacchi (2005), delimita las definiciones del concepto a dos enfoques: 1. una aproximación minimalista, que acota el término a la aplicación intencional de fuerza física, y 2. Una aproximación extensiva, que define la violencia como acto de violación de derechos. 

Una definición extensiva de la violencia más allá del uso de fuerza física, implica la transgresión de un límite, no obstante, la literatura es laxa respecto a definir qué es lo transgredido. Aunque permite observar otras formas de violencia, como simbólica o estructural, la falta de claridad conceptual conlleva la yuxtaposición de distintos planos de análisis en una situación victima-victimario. 

Aunque fuerza y violencia no pueden ser entendidos como sinónimos, un acto violento sugiere el uso deliberado de la fuerza para dañar. Definir la violencia en estos términos, tiene la ventaja de establecer un límite claro respecto a lo que es un acto de violencia, evitando la tendencia a usar el término en otras situaciones de conflicto (Bufacchi, 2005). Debido a su claridad conceptual respecto a que es la violencia, nos centraremos en esta definición.

En cuanto a como se explica la violencia, en todas las corrientes existe una tensión entre el sujeto y la estructura, o bien entre lo individual y lo colectivo, en relación a las causas y el surgimiento del fenómeno. Arteaga (2003), sitúa el espacio de la violencia en base a los conceptos de distancia y diferencia. Aunque no explica la aparición del fenómeno, la idea de distancia social permite analizar la relación entre perpetrador y víctima en base a la aparición de un otro diferente, dibujando una frontera simbólica en donde se ejerce la violencia. En este espacio, hay una dimensión de evaluación normativa, en relación a la justificación del acto violento y a la relación entre perpetrador y víctima, dibujando espacios de inclusión o exclusión respecto a frente a quienes y por qué se ejerce la violencia.

La justificación de la violencia, se define como la argumentación que fundamente una situación de violencia para desvincularlo de lo injusto, considerándolo como algo comprensible y con sentido (Basaure, 2020). Respecto la evaluación normativa de una situación de violencia, la justificación de la violencia policial se vuelve especialmente interesante, considerando que el enfrentamiento entre Carabineros y manifestantes constituye un acto de violencia intergrupal , ya que el uso de la fuerza por parte de ambos grupos tiende a reforzarse mutuamente (Gerber, González, Jiménez-Moya, Moya, & Jackson, 2018). 

### Justificaciones de la violencia policial

Estudios previos indican que la legitimidad policial (Worden & McLean, 2017) y la percepción de justicia procedimental (Tyler & Blader, 2003), predicen la aceptación pública al uso de la violencia policial. Cuando las autoridades realizan procedimientos justos y neutrales, las personas se sienten valoradas y son más propensas a acatar voluntariamente la autoridad policial (Gerber, Figuereido, Sáez, & Orchard, 2023). La legitimidad policial y la percepción de justicia procedimental, insta a los ciudadanos a aceptar el uso de la fuerza monopólica de la autoridad, pero solo cuando se mantiene dentro de ciertos límites normativos. La policía debe actuar de una forma procedimentalmente justa, pues actuar fuera de la ley eventualmente es una amenaza a su propia legitimidad (Bradford, Milani, & Jackson, 2016). En el caso de Chile, el efecto de la justicia procedimental es más fuerte en quienes se identifican como mapuches (Gerber, González, Jiménez-Moya, Moya, & Jackson, 2018).
La justificación de la violencia policial también ha sido relacionada con las teorías de justicia distributiva en el contexto chileno. Quienes perciben menor injusticia en la distribución de los ingresos de los obreros, más justifican la violencia policial de Carabineros en situaciones como usar la fuerza para desalojar liceos tomados o reprimir marchas pacíficas. No obstante, el efecto del sentido de injusticia del obrero en la justificación de reprimir marchas pacíficas, pierde relevancia al incluir el efecto de ideologías autoritarias y de dominancia social (Venegas, 2022). 

Los hallazgos más consistentes indican que los grupos minoritarios son más críticos hacia el uso de la violencia policial que los grupos mayoritarios (Arthur & Case, 1994). Otras investigaciones, sugieren que factores sociodemográficos influyen en la justificación al uso de la violencia policial. En general los hombres justifican más el uso excesivo de la fuerza policial, así como personas con menor nivel educativo y personas adultas por sobre jóvenes (Gerber, y otros, 2021).

En virtud del estado de derecho, el estándar sobre el uso de la fuerza policial es normado por tres principios básicos que gozan de reconocimiento incontrovertido: el principio de necesidad, legalidad y proporcionalidad. El primero de ellos, implica que el uso de la fuerza debe contar con un fundamento jurídico suficiente, establecido previamente por el Estado, delimitando los parámetros del uso de la fuerza. El segundo de ellos, comprende tres obligaciones: usar medios no violentos cuando sea posible, bajo el único propósito de hacer cumplir la ley, y haciendo uso de la fuerza mínima necesaria que resulte razonable en las circunstancias existentes. Finalmente, el principio de proporcionalidad, que actúa como limitante frente al ejercicio de la fuerza, pues deben actuar según la gravedad del delito (Moral Araneda, 2021).

Este límite en el uso de la fuerza policial resulta difuso, especialmente para los observadores. Sin embargo, diversas investigaciones resaltan que cuando el uso de la fuerza policial es excesivo, es decir, cuando sobrepasa la seriedad de la amenaza y el uso mínimo de la fuerza necesaria (Gerber, y otros, 2021), se necesita otro patrón de motivaciones, que está guiado por las creencias ideológicas de una persona acerca del orden social (Gerber & Jackson, 2016). 

Para abarcar las diferencias en las justificaciones del uso de la violencia policial, se puede distinguir esta según sus objetivos: entre violencia policial como control social y violencia policial como castigo (Gerber, y otros, 2021). Mientras que el uso razonable de la fuerza, proporcional a la seriedad de la amenaza, y usando el mínimo de fuerza necesario, tiene por objetivo el control social, cuando el uso de la fuerza excede la seriedad de la amenaza y el mínimo de fuerza necesario, su objetivo no es solo controlar, sino que corresponde a una forma de castigo social.

El apoyo a formas extra legales de violencia policial puede ser entendido como una respuesta punitiva, en la medida en que buscaría restaurar el estatus y las jerarquías de poder que se ven amenazadas por quienes infringen la ley (Gerber et. al., 2021).  Al saltar las normas bajo las cuales se regula la violencia policial, la respuesta punitiva no se enfoca en las características del delito o el infractor, sino en las creencias de las personas de que el orden social está bajo amenaza. 

Aunque se pueden distinguir dos motivaciones para apoyar la violencia policial, nuestra propuesta de estudio se centrará en las percepciones de violencia policial más allá de su objetivo, pues en el contexto de protesta social, ambas dimensiones expresan el apoyo a al control del orden público por parte de la policía. 

### Ideología y emociones

Aunque de larga data, el continuo izquierda-derecha se sigue utilizando para diferenciar posturas políticas en base a dos criterios básicos: 1. Su posición respecto a la igualdad. 2. La defensa hacia las costumbres (Bobbio, 1996). Para la derecha política, la desigualdad entre individuos se acepta al considerarla natural, valorando las tradiciones y costumbres.  Desde la psicología social se han reelaborado esas diferencias, proponiendo una perspectiva de la ideología como fenómeno motivado cognitivamente. El concepto ha sido definido brevemente por Erikson & Tedin (2003; Jost, Federico, & Napier, 2009) como un conjunto de creencias sobre el orden social y como este debe ser alcanzado. Las teorías de justificación sistémica (Jost, Banaji, & Nosek, 2004), han utilizado críticamente el concepto como la manera en que mitos legitimadores consensuados contribuyen a la estabilidad de jerarquías y desigualdades sociales entre grupos (Jost, Nosek, & Gosling, 2008). 

Una perspectiva de la ideología como fenómeno motivado cognitivamente pone especial énfasis en como esta refuerza necesidades o motivaciones de tipo epistémico, relacional y existencial (Jost, Ledgerwood, & Hardin, 2008), que actúan como patrones de conducta alineando actitudes, creencias y preferencias de las personas con estas necesidades. Los motivos epistémicos están relacionados a la necesidad de orden, reducir incertidumbre, complejidad o ambigüedad, la búsqueda de seguridad y orden en la vida. Las motivaciones relacionales refieren al deseo de establecer relaciones interpersonales e identificarse socialmente. Finalmente, las motivaciones existenciales, que apuntan a la necesidad por manejar circunstancias amenazadoras y a la búsqueda de seguridad y sentido (Jost, Glaser, Kruglanski, & Sulloway, 2003).  

Una serie de estudios relacionan el apoyo a actitudes conservadoras con necesidades epistémicas y relacionales como la percepción de miedo, amenaza, intolerancia a la ambigüedad, evitar la incertidumbre y la necesidad de orden. Así mismo, otros estudios (Bonano & Jost, 2006 en Jost, Federico, & Napier, 2009), sugieren que el apoyo hacia actitudes conservadores y de derecha aumentan en periodos de inestabilidad política y económica, bajo la premisa de que la sensación de amenaza activa actitudes políticas y sociales que ofrecen soluciones simples pero rígidas en materia de seguridad (Thórisdóttir & Jost, 2011).

Si la ideología es un conjunto de actitudes, valores y creencias, junto con motivaciones existenciales, epistémicas y relacionales, puede ser separada por su contenido discursivo y por su función, en cuanto las necesidades psicológicas y sociales que satisface. La relación entre contenido ideológico y función psicológica, se ordenarían como un proceso de afinidad lectiva, en donde los discursos ideológicos son seleccionados y reinterpretados en base a las motivaciones psicológicas de los individuos (Jost, Federico, & Napier, 2009).

De acuerda a Gamarra (2010; en Rottenbacher & Schmitz, 2013), para que una acción sea autoritaria, se debe cumplir una de las siguientes condiciones: 1. Debe estar presente el uso de la fuerza o algún otro tipo de mecanismo coercitivo para llevarla a cabo, 2. Debe darse un mecanismo coercitivo para llevarla a cabo, y 3. Debe estar presente la limitación, cancelación o inexistencia de un espacio de negociación entre la población y la autoridad. En este marco, el apoyo a la violencia policial en contexto de protesta, se explica bajo el razonamiento de que las manifestaciones representan una amenaza contra el orden público, la estabilidad y el orden social (Rottenbacher de Rojas & Schmitz, 2013). 

Aunque sabemos que hay un vínculo entre la percepción del miedo, conservadurismo político de derecha y justificación de la violencia policial, su relación es aun materia de discusión. El razonamiento argumentativo de esta investigación parte desde la siguiente premisa: los cambios en el clima socio-emocional, ligado a una crisis de seguridad, ha generado mayores niveles de incertidumbre y amenaza social, lo que ha provocado cambios en las percepciones hacia los actores ligados a la protesta social. Por lo que individuos que indiquen mayor miedo a manifestantes de primera línea, presentarán mayor tendencia al conservadurismo político, aumentando la probabilidad de que justifiquen la violencia policial en contexto de protesta social. 

Respecto a la relación entre estos elementos, planteamos su afinidad lectiva puede entenderse en términos de interacción: el miedo a los manifestantes de primera línea y las posturas conservadoras interactúan aumentando los chances de que los individuos justifiquen la violencia policial en contextos de protesta, en base a clasificar este tipo de actos como criminales.  
