project:
  type: website
  output-dir: docs
  
website: 
  title: "El rol del miedo y la orientación política en las justificaciones de violencia en contexto de protesta social."
  navbar: 
    left: 
      - href: index.qmd
        text: home
      - about.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc:true
    